import { describe, expect, it } from 'vitest';
import {
  decodeConfig,
  defaultConfig,
  encodeConfig,
} from '../app/configCodec';
import type {
  SequencerConfig, TrackId,
} from '../app/types';
import { TRACK_IDS } from '../app/types';

/**
 * Golden-file tests protect against silent changes to the
 * serialization format. If any of these fail, existing
 * shared URLs in the wild would break.
 */

/**
 * What the v1 golden config should decode to in the v2
 * app: same fields plus patternLength=16, all
 * trackLengths=16, version=2.
 */
function goldenConfigV1Decoded(): SequencerConfig {
  const steps = {} as Record<TrackId, string>;
  const mixer = {} as Record<TrackId, {
    gain: number; isMuted: boolean; isSolo: boolean;
    freeRun: boolean;
  }>;
  const trackLengths = {} as Record<TrackId, number>;
  for (const id of TRACK_IDS) {
    steps[id] = '1010101010101010';
    mixer[id] = {
      gain: 0.8, isMuted: false, isSolo: false,
      freeRun: false,
    };
    trackLengths[id] = 16;
  }
  return {
    version: 2,
    kitId: 'electro',
    bpm: 140,
    patternLength: 16,
    trackLengths,
    steps,
    mixer,
    swing: 0,
  };
}

/**
 * A known v2 config with varied track lengths.
 */
function goldenConfigV2(): SequencerConfig {
  const steps = {} as Record<TrackId, string>;
  const mixer = {} as Record<TrackId, {
    gain: number; isMuted: boolean; isSolo: boolean;
    freeRun: boolean;
  }>;
  const trackLengths = {} as Record<TrackId, number>;
  for (const id of TRACK_IDS) {
    steps[id] = '101010101010';
    mixer[id] = {
      gain: 0.8, isMuted: false, isSolo: false,
      freeRun: false,
    };
    trackLengths[id] = 12;
  }
  trackLengths.bd = 8;
  steps.bd = '10101010';
  trackLengths.sd = 5;
  steps.sd = '10100';
  mixer.bd.freeRun = true;
  return {
    version: 2,
    kitId: 'electro',
    bpm: 140,
    patternLength: 12,
    trackLengths,
    steps,
    mixer,
    swing: 0,
  };
}

// Generated by encoding the v1 golden config.
// If this changes, previously-shared v1 URLs break.
const GOLDEN_HASH_V1 =
  'lZFBCgIxDEXv8tdFOuBCegMXrjzBTKc6xXZamirK0LtLUR' +
  'dCuwhZ5ZFHyM-Gh0lkwwo1CNxsPs5QMM7onAIEpuihhr0U' +
  'oGwiQW0YNRQG-V91dG5z6nC9tHnocP1q8yW3ue9w1-GJOnt' +
  'jh08tXgS8fZr0S2rDdbQrlNwdBCyd7tnMUJfRkan9ObjwbcsnQ' +
  'pZAXKGGzhICV6hvYgn1fyzBcwXHFRJxj45cYWIJpbwB';

describe('golden-file tests', () => {
  it('defaultConfig() snapshot', () => {
    const config = defaultConfig();
    expect(config).toMatchSnapshot();
  });

  it('v1 hash decodes with defaults filled in', async () => {
    const decoded = await decodeConfig(GOLDEN_HASH_V1);
    expect(decoded).toEqual(goldenConfigV1Decoded());
  });

  it('v2 config round-trips identically', async () => {
    const config = goldenConfigV2();
    const hash = await encodeConfig(config);
    const decoded = await decodeConfig(hash);
    expect(decoded).toEqual(config);
  });
});

// -------------------------------------------------------
// Base64url encoding properties
// -------------------------------------------------------
describe('base64url encoding', () => {
  it('output contains no +, /, or = chars', async () => {
    const hash = await encodeConfig(defaultConfig());
    expect(hash).not.toMatch(/[+/=]/);
  });

  it('encoding is deterministic', async () => {
    const config = defaultConfig();
    const hash1 = await encodeConfig(config);
    const hash2 = await encodeConfig(config);
    expect(hash1).toBe(hash2);
  });

  it('round-trips through encode/decode', async () => {
    const config = goldenConfigV2();
    const hash = await encodeConfig(config);
    const decoded = await decodeConfig(hash);
    expect(decoded).toEqual(config);
  });
});
