import { describe, expect, it } from 'vitest';
import {
  decodeConfig,
  defaultConfig,
  encodeConfig,
} from '../app/configCodec';
import type { SequencerConfig, TrackId } from '../app/types';
import { TRACK_IDS } from '../app/types';

/**
 * Golden-file tests protect against silent changes to the
 * serialization format. If any of these fail, existing
 * shared URLs in the wild would break.
 */

/**
 * A known non-default config for golden-file testing.
 */
function goldenConfig(): SequencerConfig {
  const steps = {} as Record<TrackId, string>;
  const mixer = {} as Record<TrackId, {
    gain: number; isMuted: boolean; isSolo: boolean;
  }>;
  for (const id of TRACK_IDS) {
    steps[id] = '1010101010101010';
    mixer[id] = {
      gain: 0.8, isMuted: false, isSolo: false,
    };
  }
  return {
    version: 1,
    kitId: 'electro',
    bpm: 140,
    steps,
    mixer,
  };
}

// Generated by encoding goldenConfig() with deflate-raw.
// If this changes, all previously-shared URLs break.
const GOLDEN_HASH =
  'lZFBCgIxDEXv8tdFOuBCegMXrjzBTKc6xXZamirK0LtLUR' +
  'dCuwhZ5ZFHyM-Gh0lkwwo1CNxsPs5QMM7onAIEpuihhr0U' +
  'oGwiQW0YNRQG-V91dG5z6nC9tHnocP1q8yW3ue9w1-GJOnt' +
  'jh08tXgS8fZr0S2rDdbQrlNwdBCyd7tnMUJfRkan9ObjwbcsnQ' +
  'pZAXKGGzhICV6hvYgn1fyzBcwXHFRJxj45cYWIJpbwB';

describe('golden-file tests', () => {
  it('defaultConfig() snapshot', () => {
    const config = defaultConfig();
    expect(config).toMatchSnapshot();
  });

  it('known config encodes to known hash', async () => {
    const hash = await encodeConfig(goldenConfig());
    expect(hash).toBe(GOLDEN_HASH);
  });

  it('known hash decodes to known config', async () => {
    const decoded = await decodeConfig(GOLDEN_HASH);
    expect(decoded).toEqual(goldenConfig());
  });
});

// -------------------------------------------------------
// Base64url encoding properties
// -------------------------------------------------------
describe('base64url encoding', () => {
  it('output contains no +, /, or = chars', async () => {
    const hash = await encodeConfig(defaultConfig());
    expect(hash).not.toMatch(/[+/=]/);
  });

  it('encoding is deterministic', async () => {
    const config = defaultConfig();
    const hash1 = await encodeConfig(config);
    const hash2 = await encodeConfig(config);
    expect(hash1).toBe(hash2);
  });

  it('round-trips through encode/decode layer', async () => {
    const config = goldenConfig();
    const hash = await encodeConfig(config);
    const decoded = await decodeConfig(hash);
    expect(decoded).toEqual(config);
  });
});
