import { describe, expect, it } from 'vitest';
import {
  decodeConfig,
  defaultConfig,
  encodeConfig,
} from '../app/configCodec';

/**
 * Helper: encode a raw object bypassing validation,
 * for testing backward-compat decoding of old formats.
 */
async function encodeRaw(obj: unknown): Promise<string> {
  const json = JSON.stringify(obj);
  const stream = new Blob([json]).stream()
    .pipeThrough(new CompressionStream('deflate-raw'));
  const bytes = new Uint8Array(
    await new Response(stream).arrayBuffer()
  );
  let binary = '';
  for (const b of bytes) {
    binary += String.fromCharCode(b);
  }
  return btoa(binary)
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

/**
 * Golden-file tests protect against silent changes to the
 * serialization format. CONFIG_VERSION is now 4, so old
 * v1/v2/v3 hashes should decode to defaults.
 */

// Generated by encoding the v1 golden config.
// Now that we reject old versions, this should decode
// to defaults.
const GOLDEN_HASH_V1 =
  'lZFBCgIxDEXv8tdFOuBCegMXrjzBTKc6xXZamirK0LtLUR' +
  'dCuwhZ5ZFHyM-Gh0lkwwo1CNxsPs5QMM7onAIEpuihhr0U' +
  'oGwiQW0YNRQG-V91dG5z6nC9tHnocP1q8yW3ue9w1-GJOnt' +
  'jh08tXgS8fZr0S2rDdbQrlNwdBCyd7tnMUJfRkan9ObjwbcsnQ' +
  'pZAXKGGzhICV6hvYgn1fyzBcwXHFRJxj45cYWIJpbwB';

describe('golden-file tests', () => {
  it('defaultConfig() snapshot', () => {
    const config = defaultConfig();
    expect(config).toMatchSnapshot();
  });

  it('v1 hash decodes to defaults (rejected)',
    async () => {
      const decoded = await decodeConfig(
        GOLDEN_HASH_V1
      );
      expect(decoded).toEqual(defaultConfig());
    }
  );

  it('v2 hash decodes to defaults (rejected)',
    async () => {
      const v2Config = {
        version: 2,
        kitId: 'electro',
        bpm: 140,
        patternLength: 12,
        steps: {},
        mixer: {},
        swing: 0,
      };
      const hash = await encodeRaw(v2Config);
      const decoded = await decodeConfig(hash);
      expect(decoded).toEqual(defaultConfig());
    }
  );

  it('v3 hash decodes to defaults (rejected)',
    async () => {
      const v3Config = {
        version: 3,
        kitId: 'electro',
        bpm: 140,
        patternLength: 12,
        steps: {},
        mixer: {},
        swing: 0,
        trigConditions: {},
        parameterLocks: {},
      };
      const hash = await encodeRaw(v3Config);
      const decoded = await decodeConfig(hash);
      expect(decoded).toEqual(defaultConfig());
    }
  );

  it('v4 config round-trips identically', async () => {
    const config = defaultConfig();
    const hash = await encodeConfig(config);
    const decoded = await decodeConfig(hash);
    expect(decoded).toEqual(config);
  });
});

// -------------------------------------------------------
// Base64url encoding properties
// -------------------------------------------------------
describe('base64url encoding', () => {
  it('output contains no +, /, or = chars', async () => {
    const hash = await encodeConfig(defaultConfig());
    expect(hash).not.toMatch(/[+/=]/);
  });

  it('encoding is deterministic', async () => {
    const config = defaultConfig();
    const hash1 = await encodeConfig(config);
    const hash2 = await encodeConfig(config);
    expect(hash1).toBe(hash2);
  });

  it('round-trips through encode/decode', async () => {
    const config = defaultConfig();
    const hash = await encodeConfig(config);
    const decoded = await decodeConfig(hash);
    expect(decoded).toEqual(config);
  });
});
